$(document).ready (e) ->
  $('#file_form').on 'submit', (e) ->
    url = $('#url').val()
    token = $('#token').val()
    accept_version = $('#accept_version').val()
    method = $('#method').val()
    e.preventDefault()
    $('#response').hide()
    $('#loading').show()
    $.ajax
      type: method
      url: url
      data: new FormData(this)
      headers:
        'Accept-Version': accept_version
        'XAuthToken': token
      dataType: 'json'
      contentType: false
      cache: false
      processData: false
      success: (data) ->
        $('#response').html '<h3>Your response is</h3>' + data
        $('#loading').hide()
        $('#response').show()
        console.info data
        return
      error: (data) ->
        $('#response').html '<h2>ERROR!</h2><h3>Your response is</h3>' + data
        $('#loading').hide()
        $('#response').show()
        console.info data
        return
    return
  $('#url_form').on 'submit', (e) ->
    url = $('#url').val()
    token = $('#token').val()
    accept_version = $('#accept_version').val()
    method = $('#method').val()
    e.preventDefault()
    $('#response').hide()
    $('#loading').show()
    $.ajax
      type: method
      url: url
      data: new FormData(this)
      headers:
        'Accept-Version': accept_version
        'XAuthToken': token
      dataType: 'json'
      contentType: false
      cache: false
      processData: false
      success: (data) ->
        $('#response').html '<h3>Your response is</h3>' + data
        $('#loading').hide()
        $('#response').show()
        console.info data
        return
      error: (data) ->
        $('#response').html '<h2>ERROR!</h2><h3>Your response is</h3>' + data
        $('#loading').hide()
        $('#response').show()
        console.info data
        return
    return
  return

# ---
# generated by js2coffee 2.1.0
